modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="GNU GPL v3.0 https://github.com/bl4ckscor3/SnowUnderTrees/blob/1.16/LICENSE"

[[mods]] #mandatory
	modId="snowundertrees" #mandatory
	version="${version}" #mandatory
	displayName="Snow Under Trees" #mandatory
	description='''Adds snow under trees in snowy biomes.''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/SnowUnderTrees"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/snow-under-trees"
	authors="bl4ckscor3"

[[dependencies.snowundertrees]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowundertrees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"